quoty_user:
    resource: "@QuotyUserBundle/Resources/config/routing.yml"
    prefix:   /

quoty_quote:
    resource: "@QuotyQuoteBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern:   /login
    defaults:  { _controller: QuotyUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

about:
    pattern:   /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template: '::about.html.twig'


# tos:
#     pattern:   /tos
#     defaults:
#         _controller: FrameworkBundle:Template:template
#         template: '::tos.html.twig'

register_user:
    pattern:   /register/{token}
    defaults: { _controller: QuotyUserBundle:Account:register, token: %secret% }

register_create_user:
    pattern:   /create-user/{token}
    defaults: { _controller: QuotyUserBundle:Account:create, token: %secret% }

