security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_USER:        ROLE_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: %user_password%, roles: [ 'ROLE_USER' ] }
                    admin: { password: %admin_password%, roles: [ 'ROLE_ADMIN' ] }
        fos_userbundle:
            id: fos_user.user_manager

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

        FOS\UserBundle\Model\UserInterface:
            algorithm:   bcrypt
            iterations: 1
            encode_as_base64: false

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:  ^/
            anonymous: true
            #in_memory for dev with adminpass
            #provider:  in_memory
            provider:  fos_userbundle
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /

    access_control:
        - { path: ^/add, roles: ROLE_USER }
        - { path: ^/edit, roles: ROLE_ADMIN }
        - { path: ^/delete, roles: ROLE_ADMIN }

        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
