quoty_quote_home:
    path:     /
    defaults: { _controller: QuotyQuoteBundle:Default:viewlist }

quoty_quote_viewlist:
    path:     /
    defaults: { _controller: QuotyQuoteBundle:Default:viewlist }

quoty_quote_viewlist_slash:
    path:     /
    defaults: { _controller: QuotyQuoteBundle:Default:viewlist }

quoty_quote_view:
    path:     /view/{id}
    defaults: { _controller: QuotyQuoteBundle:Default:view, id:1 }
    requirements:
        id: \d*

quoty_quote_add:
    path:    /add
    defaults: { _controller: QuotyQuoteBundle:Default:add }

quoty_quote_edit:
    path:    /edit/{id}
    defaults: { _controller: QuotyQuoteBundle:Default:edit, id:1 }
    requirements:
        id: \d*

quoty_quote_delete:
    path:    /delete/{id}
    defaults: { _controller: QuotyQuoteBundle:Default:delete, id:1 }
    requirements:
        id: \d*

quoty_quote_tmp_error:
    path:   /tmp_error
    defaults: { _controller: QuotyQuoteBundle:Default:tmpError }