parameters:
#    quoty_user.example.class: Quoty\UserBundle\Example

services:
#    quoty_user.example:
#        class: %quoty_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    userbundle_service:
        class:     Main\UserBundle\Controller\UserBundleService
        arguments: [@fos_user.user_manager]