parameters:
#    quoty_user.example.class: Quoty\UserBundle\Example

services:
#    quoty_user.example:
#        class: %quoty_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
